import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784192215561 implements MigrationInterface {
    name = 'InitialSchema1784192215561'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "veterinarians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "specialty" character varying(255), "phone" character varying(20), "email" character varying(255), "address" text, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a68520babb0d0d23dd052e8dc76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "owners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "contact_info" character varying(255), "address" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_42838282f2e6b216301a70b02d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auth_providers_provider_enum" AS ENUM('LOCAL', 'GOOGLE', 'MICROSOFT', 'APPLE', 'FACEBOOK')`);
        await queryRunner.query(`CREATE TABLE "auth_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" "public"."auth_providers_provider_enum" NOT NULL, "provider_user_id" character varying(255), "password_hash" character varying(255), "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_cb277e892a115855fc95c373422" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_23ce9b23329d07057ec8ece6f2" ON "auth_providers" ("provider", "provider_user_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "refresh_token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "last_used_at" TIMESTAMP, "revoked_at" TIMESTAMP, "ip_address" character varying, "user_agent" character varying, "device_name" character varying, "browser" character varying, "os" character varying, CONSTRAINT "PK_9190032f6967b7971dca07d69f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('SUPER_ADMIN', 'OWNER_ADMIN', 'OWNER_USER')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "hashed_password" character varying(255), "role" "public"."users_role_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "owner_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_95ff138b88fdd8a7c9ebdb97a32" UNIQUE ("name"), CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "medicaments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "type" character varying(100) NOT NULL, "dosage_quantity" numeric(10,2), "dosage_unit" character varying, "dosage_weight" numeric(10,2), "dosage_weight_unit" character varying(20), "dosage_notes" text, "default_route" character varying, "withdrawal_period_meat" integer NOT NULL DEFAULT '0', "withdrawal_period_milk" integer NOT NULL DEFAULT '0', "manufacturer" character varying(255), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d25427d3c1387e58f9db4b23b97" UNIQUE ("name"), CONSTRAINT "PK_acdc01abf3788429a19de68cd8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "icon" character varying(10), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d5110ab69f4aacfe41fecdf4fcd" UNIQUE ("name"), CONSTRAINT "PK_ffe6b2d60596409fb08fb13830d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cattle_id" uuid NOT NULL, "event_type_id" uuid NOT NULL, "date" date NOT NULL, "description" character varying(500), "details" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_events_cattle_date" ON "events" ("cattle_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."treatments_type_enum" AS ENUM('ANTIBIOTIQUE', 'VACCIN', 'VERMIFUGE', 'ANTI_INFLAMMATOIRE', 'VITAMINE', 'AUTRE')`);
        await queryRunner.query(`CREATE TYPE "public"."treatments_dosage_unit_enum" AS ENUM('ML', 'L', 'MG', 'G', 'KG', 'COMPRIME', 'BOLUS', 'DOSE', 'UI')`);
        await queryRunner.query(`CREATE TYPE "public"."treatments_administration_route_enum" AS ENUM('IM', 'SC', 'IV', 'ORAL', 'TOPICAL', 'INTRAMAMMARY', 'INHALATION', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "treatments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cattle_id" uuid NOT NULL, "type" "public"."treatments_type_enum" NOT NULL, "date" date NOT NULL, "medicament_id" uuid NOT NULL, "dosage_quantity" numeric(10,2), "dosage_unit" "public"."treatments_dosage_unit_enum", "animal_weight" numeric(10,2), "dosage_notes" text, "administration_route" "public"."treatments_administration_route_enum" NOT NULL DEFAULT 'IM', "withdrawal_end_date" date, "veterinarian_id" uuid, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_133f26d52c70b9fa3c2dbb3c89e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_treatments_withdrawal" ON "treatments" ("withdrawal_end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_treatments_cattle_date" ON "treatments" ("cattle_id", "date") `);
        await queryRunner.query(`CREATE TABLE "herd_books" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying(100) NOT NULL, "description" text, "year" integer NOT NULL, "owner_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_40d0aac0a572d41af4968449c98" UNIQUE ("reference"), CONSTRAINT "PK_4de515b9d6611970b9d03dcff53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "herd_book_cattle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "herd_book_id" uuid NOT NULL, "cattle_id" uuid NOT NULL, "n_carnet" character varying(50), "category_id" uuid NOT NULL, "status_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_hbc_herdbook_cattle" UNIQUE ("herd_book_id", "cattle_id"), CONSTRAINT "PK_f5944293f72fe35a755dc1b240b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cattle_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cattle_id" uuid NOT NULL, "url" character varying(500) NOT NULL, "public_id" character varying(255), "position" integer NOT NULL DEFAULT '0', "is_primary" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cattle_photo_position" UNIQUE ("cattle_id", "position"), CONSTRAINT "PK_7fe80d1ad754da5f30c2891ee8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cattle_gender_enum" AS ENUM('M', 'F')`);
        await queryRunner.query(`CREATE TYPE "public"."cattle_source_type_enum" AS ENUM('ACHETE', 'NE_DANS_TROUPEAU')`);
        await queryRunner.query(`CREATE TABLE "cattle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "nickname" character varying(255), "gender" "public"."cattle_gender_enum" NOT NULL, "birth_date" date NOT NULL, "character_id" character varying(50), "brand" character varying(100), "distinctive_sign" text, "photo" character varying(500), "source_type" "public"."cattle_source_type_enum" NOT NULL, "source_supplier" character varying(255), "source_purchase_date" date, "source_purchase_price" numeric(10,2), "source_purchase_weight" numeric(10,2), "source_purchase_health_status" character varying(255), "source_purchase_notes" text, "source_mother_id" uuid, "mother_id" uuid, "father_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5e31d2911cee816f4c9fd9b44d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cattle_owner_id" ON "cattle" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cattle_gender" ON "cattle" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_cattle_birth_date" ON "cattle" ("birth_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_cattle_source_type" ON "cattle" ("source_type") `);
        await queryRunner.query(`CREATE TABLE "characters" ("id" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_86a2bcc85e3473ecf3693dfe5a1" UNIQUE ("name"), CONSTRAINT "PK_9d731e05758f26b9315dac5e378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_id" uuid NOT NULL, "cattle_id" uuid NOT NULL, "price" numeric(12,2) NOT NULL, "weight_at_purchase" numeric(8,2), "health_status" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_date" date NOT NULL, "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "invoice_number" character varying(100), "health_status" character varying(255), "notes" text, "owner_id" uuid NOT NULL, "supplier_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "contact_info" character varying(255), "phone" character varying(100), "email" character varying(255), "address" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "passport_cattle_snapshot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "passport_id" uuid NOT NULL, "herd_book_cattle_id" uuid NOT NULL, "n_carnet" character varying(50) NOT NULL, "character_name" character varying(200) NOT NULL, "name" character varying(100) NOT NULL, "brand" character varying(200), "quantity" integer NOT NULL DEFAULT '1', "snapshot_date" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_75009e753e6ce4de1b65a0b51c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_snapshot_passport" ON "passport_cattle_snapshot" ("passport_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_snapshot_herd_book_cattle" ON "passport_cattle_snapshot" ("herd_book_cattle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_snapshot_date" ON "passport_cattle_snapshot" ("snapshot_date") `);
        await queryRunner.query(`CREATE TABLE "herd_book_cattle_passport" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "passport_id" uuid NOT NULL, "herd_book_cattle_id" uuid NOT NULL, "snapshot_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_501c44851ea14fda6c6bd850018" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_hbcp_passport" ON "herd_book_cattle_passport" ("passport_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_hbcp_herd_book_cattle" ON "herd_book_cattle_passport" ("herd_book_cattle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_hbcp_snapshot" ON "herd_book_cattle_passport" ("snapshot_id") `);
        await queryRunner.query(`CREATE TYPE "public"."location_type" AS ENUM('REGION', 'DISTRICT', 'COMMUNE', 'VILLAGE')`);
        await queryRunner.query(`CREATE TABLE "location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "type" "public"."location_type" NOT NULL, "code" character varying(20), "parent_id" uuid, "region_id" uuid, "district_id" uuid, "commune_id" uuid, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_876d7bdba03c72251ec4c2dc827" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_location_type" ON "location" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_location_code" ON "location" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_location_parent" ON "location" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_location_region" ON "location" ("region_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_location_district" ON "location" ("district_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_location_commune" ON "location" ("commune_id") `);
        await queryRunner.query(`CREATE TABLE "applicant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "cin_number" character varying(50) NOT NULL, "cin_issue_date" date NOT NULL, "cin_issue_location" character varying(100) NOT NULL, "residence_commune_id" uuid, "village_id" uuid, "commune_id" uuid, "district_id" uuid, "region_id" uuid, "residence_commune" character varying(100), "village_legacy" character varying(100), "commune_legacy" character varying(100), "district_legacy" character varying(100), "region_legacy" character varying(100), "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_72718ae662675c31a384ed848ef" UNIQUE ("cin_number"), CONSTRAINT "PK_f4a6e907b8b17f293eb073fc5ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_name" ON "applicant" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_cin" ON "applicant" ("cin_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_residence_commune" ON "applicant" ("residence_commune_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_village" ON "applicant" ("village_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_commune" ON "applicant" ("commune_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_district" ON "applicant" ("district_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_applicant_region" ON "applicant" ("region_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_action" AS ENUM('CREATED', 'UPDATED', 'GENERATED', 'CANCELLED', 'USED', 'STATUS_CHANGED')`);
        await queryRunner.query(`CREATE TYPE "public"."passport_status" AS ENUM('DRAFT', 'GENERATED', 'USED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "passport_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "passport_id" uuid NOT NULL, "action" "public"."audit_action" NOT NULL, "previous_status" "public"."passport_status", "new_status" "public"."passport_status", "user_id" uuid, "ip_address" character varying(50), "user_agent" text, "metadata" json, "reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c15c98fd9e225ad5e8875b6333c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_passport" ON "passport_audit" ("passport_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_action" ON "passport_audit" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_user" ON "passport_audit" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_created_at" ON "passport_audit" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "passport" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "passport_number" character varying(50) NOT NULL, "location" character varying(100) NOT NULL, "issue_date" date NOT NULL, "district" character varying(100) NOT NULL, "applicant_id" uuid, "applicant_name" character varying(200), "cin_number" character varying(50), "cin_issue_date" date, "cin_issue_location" character varying(100), "residence_commune_id" uuid, "village_id" uuid, "commune_id" uuid, "residence_district_id" uuid, "region_id" uuid, "residence_commune" character varying(100), "village_legacy" character varying(100), "commune_legacy" character varying(100), "residence_district_legacy" character varying(100), "region_legacy" character varying(100), "purchase_commune" character varying(100) NOT NULL, "total_cattle" integer NOT NULL, "verification_date" date NOT NULL, "arrete_date" date NOT NULL, "status" "public"."passport_status" NOT NULL DEFAULT 'DRAFT', "generated_at" TIMESTAMP, "generated_by" uuid, "qr_code" character varying(500), "pdf_url" character varying(500), "herd_book_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cd4d8225844fac77d563da20059" UNIQUE ("passport_number"), CONSTRAINT "PK_48da3babc4ea0bcbb594251d892" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_passport_number" ON "passport" ("passport_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_passport_applicant" ON "passport" ("applicant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_passport_residence_commune" ON "passport" ("residence_commune_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_passport_village" ON "passport" ("village_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_passport_commune" ON "passport" ("commune_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_passport_residence_district" ON "passport" ("residence_district_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_passport_region" ON "passport" ("region_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum" AS ENUM('SUPER_ADMIN', 'OWNER_ADMIN', 'OWNER_USER')`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "role" "public"."invitations_role_enum" NOT NULL, "owner_id" uuid, "token" character varying(255) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e577dcf9bb6d084373ed3998509" UNIQUE ("token"), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auth_audit_logs_event_type_enum" AS ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'GOOGLE_LOGIN_SUCCESS', 'GOOGLE_LOGIN_FAILED', 'REFRESH_SUCCESS', 'REFRESH_FAILED', 'LOGOUT', 'SESSION_REVOKED', 'ALL_SESSIONS_REVOKED', 'REPLAY_ATTACK', 'CSRF_FAILURE', 'ACCOUNT_DISABLED', 'UNAUTHORIZED_ACCESS')`);
        await queryRunner.query(`CREATE TABLE "auth_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying, "email" character varying NOT NULL, "event_type" "public"."auth_audit_logs_event_type_enum" NOT NULL, "ip_address" character varying, "user_agent" text, "success" boolean NOT NULL, "failure_reason" text, "session_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_be11d76bd32256469e1a14a97db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb13cd2514b3c2a7a2b25bf977" ON "auth_audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_680cbf7f19e615ce2a8cde23f7" ON "auth_audit_logs" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_af3c28504a86e9fb4023c4d5b5" ON "auth_audit_logs" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1704db47d180a59c893f9aeac" ON "auth_audit_logs" ("ip_address") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a6a51aad3747b48338eaeaa00" ON "auth_audit_logs" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bde1474c0336484d13e403602" ON "auth_audit_logs" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "auth_providers" ADD CONSTRAINT "FK_262996fd08ab5a69e85b53d0055" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_sessions" ADD CONSTRAINT "FK_a7ab4fd82c654c85b9de53d971a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_e9513dcba9cfa7546ed60861ed8" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_41e317ef97c323064d6f49c1d40" FOREIGN KEY ("cattle_id") REFERENCES "cattle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_cca2d7a421ac4b1b24b9996d101" FOREIGN KEY ("event_type_id") REFERENCES "event_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatments" ADD CONSTRAINT "FK_7ebe9d4dbd49ae3518cb223b447" FOREIGN KEY ("cattle_id") REFERENCES "cattle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatments" ADD CONSTRAINT "FK_31e4ab983140487ba41e4a9287a" FOREIGN KEY ("medicament_id") REFERENCES "medicaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatments" ADD CONSTRAINT "FK_4282046ac4b12cab6ba206b008b" FOREIGN KEY ("veterinarian_id") REFERENCES "veterinarians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_books" ADD CONSTRAINT "FK_a575124ca80c019572e50842912" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" ADD CONSTRAINT "FK_0a2f19e7e3a4fea2f0e4f2fc6bd" FOREIGN KEY ("herd_book_id") REFERENCES "herd_books"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" ADD CONSTRAINT "FK_eb4333ba23eaca5e6bbd5ff19a5" FOREIGN KEY ("cattle_id") REFERENCES "cattle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" ADD CONSTRAINT "FK_4d2b4ccba3a9ded0663f51b7134" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" ADD CONSTRAINT "FK_cded2f3ca0d4a4c51a8d318824b" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cattle_photos" ADD CONSTRAINT "FK_18f7b8b713d2c7b069e3308035c" FOREIGN KEY ("cattle_id") REFERENCES "cattle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cattle" ADD CONSTRAINT "FK_cc55331a098a5cb2037d206679e" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cattle" ADD CONSTRAINT "FK_d9980c0825b66f04b80bb0d9125" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cattle" ADD CONSTRAINT "FK_b3a323533555f56b265b0ada429" FOREIGN KEY ("mother_id") REFERENCES "cattle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cattle" ADD CONSTRAINT "FK_7254b00e056497fc321cf38cdb5" FOREIGN KEY ("father_id") REFERENCES "cattle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_607211d59b13e705a673a999ab5" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_7e85c1c6dff3efaa3e91135a2b0" FOREIGN KEY ("cattle_id") REFERENCES "cattle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_ecc12cf053f9b52a0baa68437f5" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_d5fec047f705d5b510c19379b95" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_cattle_snapshot" ADD CONSTRAINT "FK_cbe52eccc245a2f36942062a4bf" FOREIGN KEY ("passport_id") REFERENCES "passport"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_cattle_snapshot" ADD CONSTRAINT "FK_ed5f3558ea943c714d9b75c4d44" FOREIGN KEY ("herd_book_cattle_id") REFERENCES "herd_book_cattle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle_passport" ADD CONSTRAINT "FK_9375bf44b3c7810d6d2a690b21e" FOREIGN KEY ("passport_id") REFERENCES "passport"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle_passport" ADD CONSTRAINT "FK_91cacfbe400d634d6a5cf13b0dc" FOREIGN KEY ("herd_book_cattle_id") REFERENCES "herd_book_cattle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle_passport" ADD CONSTRAINT "FK_3eb492da4ab0d22e974f4f76344" FOREIGN KEY ("snapshot_id") REFERENCES "passport_cattle_snapshot"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_92137b1457c0969fe2d20a9faff" FOREIGN KEY ("parent_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_ab3992c15a52ae2062c349f189d" FOREIGN KEY ("region_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_828664dee332d2dc0499a1bd5e2" FOREIGN KEY ("district_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "FK_94991d081ac7dea91c62b1a835d" FOREIGN KEY ("commune_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_8ce128bed0d982c64ba7f23b258" FOREIGN KEY ("residence_commune_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_56592ca10105192b9bb2ff86b34" FOREIGN KEY ("village_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_19b1709547016b182702157d417" FOREIGN KEY ("commune_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_0b97ff876baf1166e189232e5a6" FOREIGN KEY ("district_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_ebf115121007d4ac67ff28393b6" FOREIGN KEY ("region_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_audit" ADD CONSTRAINT "FK_447a680fb1ff690a8ae06eaf86c" FOREIGN KEY ("passport_id") REFERENCES "passport"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_audit" ADD CONSTRAINT "FK_18645f200d02d49cf6f1f6757b6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_9aa80e1b19163163d6850053a0d" FOREIGN KEY ("applicant_id") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_7469efe690492876376506f8d5e" FOREIGN KEY ("residence_commune_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_69fe0c260dab27e0f768a4573ff" FOREIGN KEY ("village_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_9962f026f4db9141a06d9b4375f" FOREIGN KEY ("commune_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_8f95a897ba220bd4e8ec99962b5" FOREIGN KEY ("residence_district_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_60c41ec25ca2167e602d78e2581" FOREIGN KEY ("region_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_d25957c526bddd62127177dbd57" FOREIGN KEY ("generated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport" ADD CONSTRAINT "FK_921b4a75f39781fdad083445d68" FOREIGN KEY ("herd_book_id") REFERENCES "herd_books"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_921b4a75f39781fdad083445d68"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_d25957c526bddd62127177dbd57"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_60c41ec25ca2167e602d78e2581"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_8f95a897ba220bd4e8ec99962b5"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_9962f026f4db9141a06d9b4375f"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_69fe0c260dab27e0f768a4573ff"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_7469efe690492876376506f8d5e"`);
        await queryRunner.query(`ALTER TABLE "passport" DROP CONSTRAINT "FK_9aa80e1b19163163d6850053a0d"`);
        await queryRunner.query(`ALTER TABLE "passport_audit" DROP CONSTRAINT "FK_18645f200d02d49cf6f1f6757b6"`);
        await queryRunner.query(`ALTER TABLE "passport_audit" DROP CONSTRAINT "FK_447a680fb1ff690a8ae06eaf86c"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_ebf115121007d4ac67ff28393b6"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_0b97ff876baf1166e189232e5a6"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_19b1709547016b182702157d417"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_56592ca10105192b9bb2ff86b34"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_8ce128bed0d982c64ba7f23b258"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_94991d081ac7dea91c62b1a835d"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_828664dee332d2dc0499a1bd5e2"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_ab3992c15a52ae2062c349f189d"`);
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "FK_92137b1457c0969fe2d20a9faff"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle_passport" DROP CONSTRAINT "FK_3eb492da4ab0d22e974f4f76344"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle_passport" DROP CONSTRAINT "FK_91cacfbe400d634d6a5cf13b0dc"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle_passport" DROP CONSTRAINT "FK_9375bf44b3c7810d6d2a690b21e"`);
        await queryRunner.query(`ALTER TABLE "passport_cattle_snapshot" DROP CONSTRAINT "FK_ed5f3558ea943c714d9b75c4d44"`);
        await queryRunner.query(`ALTER TABLE "passport_cattle_snapshot" DROP CONSTRAINT "FK_cbe52eccc245a2f36942062a4bf"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_d5fec047f705d5b510c19379b95"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_ecc12cf053f9b52a0baa68437f5"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_7e85c1c6dff3efaa3e91135a2b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_607211d59b13e705a673a999ab5"`);
        await queryRunner.query(`ALTER TABLE "cattle" DROP CONSTRAINT "FK_7254b00e056497fc321cf38cdb5"`);
        await queryRunner.query(`ALTER TABLE "cattle" DROP CONSTRAINT "FK_b3a323533555f56b265b0ada429"`);
        await queryRunner.query(`ALTER TABLE "cattle" DROP CONSTRAINT "FK_d9980c0825b66f04b80bb0d9125"`);
        await queryRunner.query(`ALTER TABLE "cattle" DROP CONSTRAINT "FK_cc55331a098a5cb2037d206679e"`);
        await queryRunner.query(`ALTER TABLE "cattle_photos" DROP CONSTRAINT "FK_18f7b8b713d2c7b069e3308035c"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" DROP CONSTRAINT "FK_cded2f3ca0d4a4c51a8d318824b"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" DROP CONSTRAINT "FK_4d2b4ccba3a9ded0663f51b7134"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" DROP CONSTRAINT "FK_eb4333ba23eaca5e6bbd5ff19a5"`);
        await queryRunner.query(`ALTER TABLE "herd_book_cattle" DROP CONSTRAINT "FK_0a2f19e7e3a4fea2f0e4f2fc6bd"`);
        await queryRunner.query(`ALTER TABLE "herd_books" DROP CONSTRAINT "FK_a575124ca80c019572e50842912"`);
        await queryRunner.query(`ALTER TABLE "treatments" DROP CONSTRAINT "FK_4282046ac4b12cab6ba206b008b"`);
        await queryRunner.query(`ALTER TABLE "treatments" DROP CONSTRAINT "FK_31e4ab983140487ba41e4a9287a"`);
        await queryRunner.query(`ALTER TABLE "treatments" DROP CONSTRAINT "FK_7ebe9d4dbd49ae3518cb223b447"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_cca2d7a421ac4b1b24b9996d101"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_41e317ef97c323064d6f49c1d40"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_e9513dcba9cfa7546ed60861ed8"`);
        await queryRunner.query(`ALTER TABLE "refresh_sessions" DROP CONSTRAINT "FK_a7ab4fd82c654c85b9de53d971a"`);
        await queryRunner.query(`ALTER TABLE "auth_providers" DROP CONSTRAINT "FK_262996fd08ab5a69e85b53d0055"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bde1474c0336484d13e403602"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a6a51aad3747b48338eaeaa00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1704db47d180a59c893f9aeac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af3c28504a86e9fb4023c4d5b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_680cbf7f19e615ce2a8cde23f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb13cd2514b3c2a7a2b25bf977"`);
        await queryRunner.query(`DROP TABLE "auth_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."auth_audit_logs_event_type_enum"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_region"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_residence_district"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_commune"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_village"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_residence_commune"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_applicant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_passport_number"`);
        await queryRunner.query(`DROP TABLE "passport"`);
        await queryRunner.query(`DROP TYPE "public"."passport_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_passport"`);
        await queryRunner.query(`DROP TABLE "passport_audit"`);
        await queryRunner.query(`DROP TYPE "public"."audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_region"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_district"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_commune"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_village"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_residence_commune"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_cin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_applicant_name"`);
        await queryRunner.query(`DROP TABLE "applicant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_location_commune"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_location_district"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_location_region"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_location_parent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_location_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_location_type"`);
        await queryRunner.query(`DROP TABLE "location"`);
        await queryRunner.query(`DROP TYPE "public"."location_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hbcp_snapshot"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hbcp_herd_book_cattle"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_hbcp_passport"`);
        await queryRunner.query(`DROP TABLE "herd_book_cattle_passport"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_snapshot_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_snapshot_herd_book_cattle"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_snapshot_passport"`);
        await queryRunner.query(`DROP TABLE "passport_cattle_snapshot"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP TABLE "characters"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cattle_source_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cattle_birth_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cattle_gender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cattle_owner_id"`);
        await queryRunner.query(`DROP TABLE "cattle"`);
        await queryRunner.query(`DROP TYPE "public"."cattle_source_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cattle_gender_enum"`);
        await queryRunner.query(`DROP TABLE "cattle_photos"`);
        await queryRunner.query(`DROP TABLE "herd_book_cattle"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "herd_books"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatments_cattle_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatments_withdrawal"`);
        await queryRunner.query(`DROP TABLE "treatments"`);
        await queryRunner.query(`DROP TYPE "public"."treatments_administration_route_enum"`);
        await queryRunner.query(`DROP TYPE "public"."treatments_dosage_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."treatments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_events_cattle_date"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TABLE "event_types"`);
        await queryRunner.query(`DROP TABLE "medicaments"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "refresh_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23ce9b23329d07057ec8ece6f2"`);
        await queryRunner.query(`DROP TABLE "auth_providers"`);
        await queryRunner.query(`DROP TYPE "public"."auth_providers_provider_enum"`);
        await queryRunner.query(`DROP TABLE "owners"`);
        await queryRunner.query(`DROP TABLE "veterinarians"`);
    }

}
